fix: Ingredient ViewSet, Serializer 데이터 고도화
cancook/cancook-backend pull request #20
Opened 2023-07-08 05:53 UTC by 2044smile

2023-07-12 13:11 UTC, 2044smile commented
@DevDior

문제없이 실행 될거야 문제 있으면 바로바로 알려줘!

2023-07-13 14:20 UTC, DevDior requested changes
단어 검색하면 재료 연관 검색어 도출하는 API가 삭제돼있어서
이거 다시 살리고 머지 해야할 것 같아

2023-07-13 14:20 UTC, DevDior commented on search/models.py
> +    ingredients = models.ForeignKey(Ingredients, on_delete=models.PROTECT)
우리 나중에 이상 재료 삭제해야 하는데, 그때 문제는 없으려나?

2023-07-13 14:20 UTC, DevDior commented on search/urls.py
> -router.register('ingredient-list', views.IngredientViewSet, basename='ingredient')
이거 그 연관 검색 view인데 삭제하면 안돼ㅠㅠ

2023-07-13 14:20 UTC, DevDior commented on search/serializers.py
> -class IngredientSerializer(serializers.ModelSerializer):
이거 연관 검색 알려주는 view에서 사용하는 serializer라 삭제하면 안돼ㅜ

2023-07-13 14:20 UTC, DevDior commented on search/views.py
> -class IngredientViewSet(mixins.ListModelMixin, viewsets.GenericViewSet):
아 연관검색어 API 삭제하고 재료 기반 레시피 API로 바꿨구나
둘 다 있어야 해 형

2023-07-14 09:41 UTC, 2044smile commented on search/models.py
> +    ingredients = models.ForeignKey(Ingredients, on_delete=models.PROTECT)
CASCADE 로 변경했어

2023-07-14 10:12 UTC, 2044smile commented
@DevDior 다시 전 데이터로 돌려놨어

2023-07-15 03:25 UTC, DevDior requested changes
나도 최근에야 Serializer Validation에 대해서 제대로 사용하기 시작했고 이걸 또 Swagger랑 연결했는데 코드도 깔끔하고 serializer 하나도 많은 걸 할 수 있어서 좋은 것 같아

뭔가 뷰 코드를 짤 때, serializer 하나로 input 검증과 Response도 다 처리하면서 Swagger랑도 연동하는 걸 원해서 우리 서비스에서 사용하려 했었는데, 여기에서도 안되는 게 하나 있어서 이걸 못했거든? 다음에 이거 이야기해봐도 좋겠다

2023-07-15 03:25 UTC, DevDior commented on search/views.py
>      @swagger_auto_schema(query_serializer=WordValidationSerializer)
@swagger_auto_schema(query_serializer=WordValidationSerializer)
query_serializer가 GET Query parameter를 serializer랑 연결해서 보여주는 기능인데
이건 word를 GET Method parameter로 받기 때문에 GetIngredientDataViewSet의 list에 데코레이트를 해줘야 Swagger가 맞게 동작할 거야

GetYouTubeFromIngredientViewSet랑은 맞지 않은 것 같은데
이 뷰를 GET Method로 한다면 query_serializer=형이 사용할 validation serializer
아마 POST Method나 PATCH 등의 다른 Method를 사용한다면 이제 body를 받아야 하니까
request_body=형이 사용할 validation serializer를 적용하면 Swagger에서 적절하게 표현될 것 같아

추가로 이 뷰에서 GET을 사용한다면 parameter, 다른 Method를 사용한다면 data를 받을텐데, 그 Validation Serializer를 작성한다면 serializers.ListField(child=serializers.CharField())를 사용하면 좋을 것 같아
ex) ingredientLIst = serializers.ListField(child=serializers.CharField())

이렇게 하면 view단에서 input parameter나 data가 list인지 list 안의 요소들이 charater인지 serializer.is_valid()할 때, 검증해주거든 시도해보진 않았지만 Swagger에서도 연동돼서 String이 아니라 List나 Array를 요청하라고 표시될 거야!

2023-07-15 03:25 UTC, DevDior commented on search/views.py
> +        return Response(ingredient_list, status=200)
밑에 get_queryset 함수를 여기로 옮긴다면 queryset이랑 serializer가 위 두 줄로 다 끝나서 더 할 게 없어서
return Response(serializer.data, status=200)이면 딱 깔끔하게 끝날 것 같아

2023-07-15 05:33 UTC, 2044smile commented on search/views.py
> +        return Response(ingredient_list, status=200)
```
class GetIngredientDataViewSet(mixins.ListModelMixin, viewsets.GenericViewSet):
    queryset = Ingredients.objects.all()
    serializer_class = GetIngredientDataSerializer

    def get_queryset(self):
        queryset = self.queryset.values('name')
        return queryset

    def list(self, request):
        queryset = self.get_queryset()
        serializer = self.get_serializer(queryset, many=True)
        # [!]
        ingredient_list = []

        validated_data = serializer.data
        for data in validated_data:
            target = list(data.values())
            ingredient_list.append(target[0])
        # [!]
```

# [!] 코드가 제거되면 사진_1 과 같은 결과가 나와
이걸 원하는 건가?

![image](https://github.com/cancook/cancook-backend/assets/47213853/c36ed9c3-671e-45c0-88b3-0a2cf5176541)

나는 프론트와 재료 데이터 얘기가 안되서 아래 사진과 같이 바꿨거든

![image](https://github.com/cancook/cancook-backend/assets/47213853/4973562d-ada0-4a77-8285-d8b08a51ea5e)

2023-07-15 05:43 UTC, 2044smile commented
코드 수정했고, WordValidationSerializer 쪽도 ListField(CharField) 식으로 변경했어.

GetYouTubuFromIngredientViewSet 을 수정해서 작업하면 돼!

2023-07-27 13:25 UTC, DevDior approved these changes

2023-07-27 13:25 UTC, merged